### ISSUE TITLE
ItemCount for Rounds/Arrows etc.

### ISSUE THREAD

**Issue by Kahuma1** [Sattva-108/AdiBags#12]
![svatshells](https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5/assets/92261432/95cf72a2-3592-4391-ab1a-38623a5cb3b6)
Is it possible to disable Itemlvl(similar to heirlooms) or move the Itemcount to a different position? I know there is the option for minimum itemlvl but i would like to continue to see item lvl for every item not only those above 231( ammo hast 230)
Atm the Itemlvl overlapps with the Itemcount, which is especially annoying for Arrows and Rounds. Since they have such a big number, maybe there is also a way to shorten that? from 10000 to 10K?
I am aware that you could just move the Itemlvl to a different position, but that looks kinda dumb xD
Ty

**Comment by Sattva-108** [comment]
I added option to hide ilvl for ammo, good request.

Direct Download (itemLevel-ammo branch):
 https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5/archive/refs/heads/itemLevel-ammo.zip

commit: https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5/commit/6f2e650bfb5a394b8dce07ea60c6d04d3a3a5e35?diff=unified&w=1

**Comment by Kahuma1** [comment]
Works great, thanks
